<?xml version="1.0" encoding="utf-8"?><Database Name="ESS_ERP" Class="ESS_POSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=59.173.0.98;Initial Catalog=ESS_ERP;Persist Security Info=True;User ID=sa" SettingsObjectName="ESS.Domain.POP.Properties.Settings" SettingsPropertyName="ESS_ERPConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Pop.TemplateBody" Member="TemplateBody">
    <Type Name="TemplateBody">
      <Column Name="Guid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FontName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FontSize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FontStyle" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FontColor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="XPosition" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="YPosition" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewFilePath" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OldFilePath" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FontAlignment" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Seq" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HeadGuid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Pop.EmptyTemplate" Member="EmptyTemplate">
    <Type Name="EmptyTemplate">
      <Column Name="Guid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ImageFileDir" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ImageFileName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Seq" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsEnable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Pop.TemplateHead" Member="TemplateHead">
    <Type Name="TemplateHead">
      <Column Name="Guid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ImageFileDir" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ImageFileName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Seq" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsEnable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParialViewDir" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ParialViewName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>